language: python
sudo: false

branches: master  # This way push builds will only run on master branch. Does not affect PR builds.

env:
  - TOX_ENV=flake8
  - TOX_ENV=py34-latest
  - TOX_ENV=py37-latest
  # Django 2
  - TOX_ENV=py34-dj2-cms35
  - TOX_ENV=py34-dj2-cms36
  - TOX_ENV=py34-dj2-cms37
  - TOX_ENV=py37-dj2-cms35
  - TOX_ENV=py37-dj2-cms36
  - TOX_ENV=py37-dj2-cms37
  # Django 2.1
  - TOX_ENV=py34-dj21-cms35
  - TOX_ENV=py34-dj21-cms36
  - TOX_ENV=py34-dj21-cms37
  - TOX_ENV=py37-dj21-cms35
  - TOX_ENV=py37-dj21-cms36
  - TOX_ENV=py37-dj21-cms37
  # Django 2.2
  - TOX_ENV=py34-dj22-cms35
  - TOX_ENV=py34-dj22-cms36
  - TOX_ENV=py34-dj22-cms37
  - TOX_ENV=py37-dj22-cms35
  - TOX_ENV=py37-dj22-cms36
  - TOX_ENV=py37-dj22-cms37
  # Django 3.1
  - TOX_ENV=py37-dj31-cms37
  - TOX_ENV=py37-dj31-cms38
  - TOX_ENV=py38-dj31-cms37
  - TOX_ENV=py38-dj31-cms38

install:
  - pip install tox coverage

script:
  - tox -e $TOX_ENV

#after_success:
#  - bash <(curl -s https://codecov.io/bash)