# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    replaces = [('layouter', '0001_initial'), ('layouter', '0002_equal_height'), ('layouter', '0003_auto_20190129_1002'), ('layouter', '0004_background_options')]

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='layouter_containerplugin', serialize=False, to='cms.CMSPlugin')),
                ('container_type', models.IntegerField(choices=[(0, 'One tile - full width'), (1, 'Two tiles - 50 | 50'), (2, 'Two tiles - 25 | 75'), (3, 'Two tiles - 75 | 25'), (4, 'Two tiles - 33 | 66'), (5, 'Two tiles - 66 | 33'), (6, 'Three tiles - 33 | 33 | 33'), (7, 'Three tiles - 25 | 25 | 50'), (8, 'Three tiles - 25 | 50 | 25'), (9, 'Three tiles - 50 | 25 | 25'), (10, 'Four tiles - 25 | 25 | 25 | 25')], default=[100])),
                ('margin', models.IntegerField(choices=[(0, 'No margin'), (1, '8.33%'), (2, '16.66%'), (3, '25%'), (4, '33.33%')], default=0, help_text='How much margin is needed on the left and right side?')),
                ('css_classes', models.CharField(blank=True, max_length=512, null=True)),
                ('equal_height', models.BooleanField(default=False, help_text='Align height of all columns in this row. Please note: This setting is not  supported by Internet Explorer 9 and below.', verbose_name='Align Content Height')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Background image')),
                ('background_image_height', models.IntegerField(blank=True, default=1080, help_text='It is recommended to limit the size of the background image to a reasonable number in order to reduce page loading times.', null=True, verbose_name='Background image width')),
                ('background_image_parallax', models.IntegerField(choices=[(0, 'No effect'), (1, 'Static background image'), (2, 'Parallax background image')], default=0, verbose_name='Parallax Effect')),
                ('background_image_width', models.IntegerField(blank=True, default=1920, null=True, verbose_name='Background image width')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
