# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouter', '0002_equal_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerplugin',
            name='margin',
            field=models.IntegerField(choices=[(0, 'No margin'), (1, '8.33%'), (2, '16.66%'), (3, '25%'), (4, '33.33%')], default=0, help_text='How much margin is needed on the left and right side?'),
        ),
    ]
