# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouter', '0002_equal_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerplugin',
            name='disable_on_desktop',
            field=models.BooleanField(default=False, verbose_name='Disable on desktop'),
        ),
        migrations.AddField(
            model_name='containerplugin',
            name='disable_on_mobile',
            field=models.BooleanField(default=False, verbose_name='Disable on mobile'),
        ),
        migrations.AddField(
            model_name='containerplugin',
            name='disable_on_tablet',
            field=models.BooleanField(default=False, verbose_name='Disable on tablet'),
        ),
        migrations.AlterField(
            model_name='containerplugin',
            name='margin',
            field=models.IntegerField(choices=[(0, 'No margin'), (1, '8.33%'), (2, '16.66%'), (3, '25%'), (4, '33.33%')], default=0, help_text='How much margin is needed on the left and right side?'),
        ),
    ]
