# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-05 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('layouter', '0003_auto_20190129_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerplugin',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Background image'),
        ),
        migrations.AddField(
            model_name='containerplugin',
            name='background_image_height',
            field=models.IntegerField(blank=True, default=1080, help_text='It is recommended to limit the size of the background image to a reasonable number in order to reduce page loading times.', null=True, verbose_name='Background image width'),
        ),
        migrations.AddField(
            model_name='containerplugin',
            name='background_image_parallax',
            field=models.IntegerField(choices=[(0, 'No effect'), (1, 'Static background image'), (2, 'Parallax background image')], default=0, verbose_name='Parallax Effect'),
        ),
        migrations.AddField(
            model_name='containerplugin',
            name='background_image_width',
            field=models.IntegerField(blank=True, default=1920, null=True, verbose_name='Background image width'),
        ),
    ]
