# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('layouter', '0004_background_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerplugin',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Background image'),
        ),
    ]
